language: python
python: "3.4"
env:
  - TOXENV=py26-1.4
  - TOXENV=py26-1.5
  - TOXENV=py26-1.6
  - TOXENV=py27-1.4
  - TOXENV=py27-1.5
  - TOXENV=py27-1.6
  - TOXENV=py33-1.5
  - TOXENV=py33-1.6
  - TOXENV=py34-1.5
  - TOXENV=py34-1.6
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
